name: Set Webhook Secret (executar 1x)

on:
  workflow_dispatch:
    inputs:
      webhook_secret:
        description: 'Valor do WEBHOOK_SECRET'
        required: true
        type: string

jobs:
  set-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set WEBHOOK_SECRET no Fly.io
        run: flyctl secrets set WEBHOOK_SECRET=${{ github.event.inputs.webhook_secret }} --app hub-granmarquise
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
